"""Artifact endpoints - tree listing, file content, ZIP export."""

from __future__ import annotations

import io
import logging
import zipfile

from fastapi import APIRouter, Depends, Path, Query
from fastapi.responses import JSONResponse, StreamingResponse
from starlette.concurrency import run_in_threadpool

from shared_lib.auth import current_user_id
from shared_lib.storage import is_cosmos_enabled

from services.files import get_file_repository
from services.runs import get_run_repository
from services.sdd import generate_sdd_docx
from services.storage import download_blob, list_blobs


logger = logging.getLogger(__name__)
router = APIRouter()


def _require_storage():
    if not is_cosmos_enabled():
        return JSONResponse(
            status_code=503,
            content={
                "ok": False,
                "error": {
                    "code": "COSMOS_DISABLED",
                    "message": "Cosmos DB not configured.",
                },
            },
        )
    return None


# ---------------------------------------------------------------------------
# Artifact tree (list files generated by a run)
# ---------------------------------------------------------------------------

@router.get("/api/codegen/runs/{run_id}/artifacts/tree")
async def get_artifact_tree(
    run_id: str = Path(...),
    user_id: str = Depends(current_user_id),
):
    blocked = _require_storage()
    if blocked:
        return blocked

    run = get_run_repository().get_any(run_id)
    if run is None:
        return JSONResponse(
            status_code=404,
            content={
                "ok": False,
                "error": {
                    "code": "NOT_FOUND",
                    "message": "Run not found.",
                },
            },
        )

    if not run.artifact_blob_root:
        return {
            "ok": True,
            "tree": [],
            "file_count": 0,
        }

    prefix = run.artifact_blob_root
    if not prefix.endswith("/"):
        prefix += "/"

    blob_names = list_blobs(prefix)

    # Convert to relative paths
    tree = []
    for name in sorted(blob_names):
        rel = name[len(prefix):]
        if rel:
            size = 0  # Size would require individual blob properties call; skip for listing
            tree.append({
                "path": rel,
                "name": rel.split("/")[-1],
            })

    return {
        "ok": True,
        "tree": tree,
        "file_count": len(tree),
        "blob_root": run.artifact_blob_root,
    }


# ---------------------------------------------------------------------------
# Read a single artifact file
# ---------------------------------------------------------------------------

@router.get("/api/codegen/runs/{run_id}/artifacts/file")
async def get_artifact_file(
    run_id: str = Path(...),
    path: str = Query(..., description="Relative file path within the artifact root"),
    user_id: str = Depends(current_user_id),
):
    blocked = _require_storage()
    if blocked:
        return blocked

    run = get_run_repository().get_any(run_id)
    if run is None:
        return JSONResponse(
            status_code=404,
            content={
                "ok": False,
                "error": {
                    "code": "NOT_FOUND",
                    "message": "Run not found.",
                },
            },
        )

    if not run.artifact_blob_root:
        return JSONResponse(
            status_code=404,
            content={
                "ok": False,
                "error": {
                    "code": "NO_ARTIFACTS",
                    "message": "No artifacts for this run.",
                },
            },
        )

    blob_path = f"{run.artifact_blob_root}/{path}"
    data = download_blob(blob_path)

    if data is None:
        return JSONResponse(
            status_code=404,
            content={
                "ok": False,
                "error": {
                    "code": "FILE_NOT_FOUND",
                    "message": f"File '{path}' not found.",
                },
            },
        )

    # Try to decode as text
    try:
        content = data.decode("utf-8")
        return {
            "ok": True,
            "path": path,
            "content": content,
        }
    except UnicodeDecodeError:
        return StreamingResponse(
            io.BytesIO(data),
            media_type="application/octet-stream",
            headers={
                "Content-Disposition": f'attachment; filename="{path.split("/")[-1]}"'
            },
        )


# ---------------------------------------------------------------------------
# Export all artifacts as ZIP
# ---------------------------------------------------------------------------

@router.post("/api/codegen/runs/{run_id}/export/zip")
async def export_zip(
    run_id: str = Path(...),
    user_id: str = Depends(current_user_id),
):
    blocked = _require_storage()
    if blocked:
        return blocked

    run = get_run_repository().get_any(run_id)
    if run is None:
        return JSONResponse(
            status_code=404,
            content={
                "ok": False,
                "error": {
                    "code": "NOT_FOUND",
                    "message": "Run not found.",
                },
            },
        )

    if not run.artifact_blob_root:
        return JSONResponse(
            status_code=404,
            content={
                "ok": False,
                "error": {
                    "code": "NO_ARTIFACTS",
                    "message": "No artifacts for this run.",
                },
            },
        )

    prefix = run.artifact_blob_root
    if not prefix.endswith("/"):
        prefix += "/"

    blob_names = list_blobs(prefix)

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for name in sorted(blob_names):
            rel = name[len(prefix):]
            if not rel:
                continue

            data = download_blob(name)
            if data:
                zf.writestr(rel, data)

    buf.seek(0)
    filename = f"codegen-{run_id[:8]}.zip"

    return StreamingResponse(
        buf,
        media_type="application/zip",
        headers={
            "Content-Disposition": f'attachment; filename="{filename}"',
        },
    )


# ---------------------------------------------------------------------------
# Export the Solution Design Document (SDD) as .docx
# ---------------------------------------------------------------------------

_DOCX_MEDIA = (
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
)


def _extract_input_text(filename: str, data: bytes) -> str:
    """Best-effort text extraction from a run's input file for the SDD process description.

    Handles text/markdown/json and .docx (python-docx); other binaries are skipped.
    """
    name = (filename or "").lower()

    if name.endswith((".md", ".markdown", ".txt", ".json", ".csv")):
        try:
            return data.decode("utf-8")
        except UnicodeDecodeError:
            return ""

    if name.endswith(".docx"):
        try:
            from docx import Document

            doc = Document(io.BytesIO(data))
            lines = [p.text for p in doc.paragraphs if p.text.strip()]

            for table in doc.tables:
                for row in table.rows:
                    cells = [c.text.strip() for c in row.cells]
                    if any(cells):
                        lines.append(" | ".join(cells))

            return "\n".join(lines)
        except Exception:
            return ""

    return ""


@router.post("/api/codegen/runs/{run_id}/export/sdd")
async def export_sdd(
    run_id: str = Path(...),
    user_id: str = Depends(current_user_id),
):
    """Generate a Solution Design Document (.docx) for a run from its input
    files / approved SDD (the authoritative design spec that drove code generation).
    Runs the S-agent SDD pipeline one-shot (auto-selects the recommended solution option).
    """
    blocked = _require_storage()
    if blocked:
        return blocked

    run = get_run_repository().get_any(run_id)
    if run is None:
        return JSONResponse(
            status_code=404,
            content={
                "ok": False,
                "error": {
                    "code": "NOT_FOUND",
                    "message": "Run not found.",
                },
            },
        )

    # Build the process description from the workflow's input files.
    files = get_file_repository().list(run.workflow_id)
    parts = []

    for f in files:
        if not f.blob_path:
            continue

        data = download_blob(f.blob_path)
        if not data:
            continue

        text = _extract_input_text(f.filename, data)
        if text.strip():
            parts.append(f"=== Source: {f.filename} ===\n{text}")

    process_description = "\n\n".join(parts).strip()

    if not process_description:
        return JSONResponse(
            status_code=404,
            content={
                "ok": False,
                "error": {
                    "code": "NO_SPEC",
                    "message": (
                        "No readable specification/SDD input files for this "
                        "run to build a final SDD export from."
                    ),
                },
            },
        )

    try:
        docx = await run_in_threadpool(
            generate_sdd_docx,
            process_description,
        )
    except RuntimeError as exc:
        logger.warning("[sdd] generation unavailable: %s", exc)
        return JSONResponse(
            status_code=503,
            content={
                "ok": False,
                "error": {
                    "code": "AI_UNAVAILABLE",
                    "message": str(exc),
                },
            },
        )
    except Exception:
        logger.exception("[sdd] generation failed run=%s", run_id)
        return JSONResponse(
            status_code=500,
            content={
                "ok": False,
                "error": {
                    "code": "SDD_FAILED",
                    "message": "SDD generation failed.",
                },
            },
        )

    filename = f"SDD-{run_id[:8]}.docx"

    return StreamingResponse(
        io.BytesIO(docx),
        media_type=_DOCX_MEDIA,
        headers={
            "Content-Disposition": f'attachment; filename="{filename}"',
        },
    )
